baseURL = 'https://pascobyte.blog/'
languageCode = 'en-us'
title = 'PascoByte'
theme = 'techblog'
disableKinds = ["taxonomy", "term"]
disableHugoGeneratorInject = true
minifyOutput = true
enableRobotsTXT = true

[params]
  tagline = "Emerging Technologies and Technology Trends"
  headline = "PascoByte: The Future of Technology is Now"
  intro = "Explore the latest emerging technologies and technology trends with PascoByte, a technology website and blog. Learn about the latest innovations and how they are changing the world, from artificial intelligence to machine learning to robotics. PascoByte is your one-stop shop for all things technology."
  description = "Stay up-to-date on the latest emerging technologies and technology trends with PascoByte, a technology website and blog. Learn about the latest innovations and how they are changing the world."
  logo = "/images/pascobyte-logo.svg"
  bio = "/my-mission/"
  contact = "https://forms.gle/a6Qb3MYyLbNuFMDDA"
  github = "https://github.com/pascobyte"
  opensea = "https://opensea.io/PascoByte"
  tiktok = "https://www.tiktok.com/@pascobyte"
  youtube = "https://www.youtube.com/channel/UCcPpjsmSJS9p3o9LbLgemaw"

[permalinks]
  chatgpt = "/:filename/"


[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = false