baseURL = 'https://pascobyte.blog/'
languageCode = 'en-us'
title = 'PascoByte'
theme = 'techblog'
disableKinds = ["taxonomy", "term"]
disableHugoGeneratorInject = true
minifyOutput = true
enableRobotsTXT = true

[params]
  tagline = "Exploring Tech Frontiers"
  headline = "Embarking on Tech Adventures"
  intro = "Greetings, curious minds! Welcome to PascoByte, your compass in the realm of tech exploration. Here, we're all about diving deep into the ever-evolving world of technology. From AI wonders to emerging trends that light up the horizon, we're here to fuel your tech curiosity."
  description = "Your hub for the latest in AI, emerging tech trends, and more. Join us in navigating the exciting world of technology at PascoByte."
  logo = "/images/pascobyte-logo.svg"
  bio = "/my-mission/"
  contact = "https://forms.gle/a6Qb3MYyLbNuFMDDA"
  twitter = "https://twitter.com/pascobyte"
  twitterhandle = "@pascobyte"
  github = "https://github.com/pascobyte"
  opensea = "https://opensea.io/PascoByte"

[permalinks]
  chatgpt = "/:filename/"


[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = false