baseURL = 'https://pascobyte.blog/'
languageCode = 'en-us'
title = 'PascoByte'
theme = 'techblog'
disableKinds = ["taxonomy", "term"]
disableHugoGeneratorInject = true
minifyOutput = false
enableRobotsTXT = true

[params]
  tagline = "Simplicity Meets Purpose"
  description = "Welcome to PascoByte, where simplicity meets purpose in every line of code. Explore streamlined solutions that tackle problems with elegance and efficiency."
  logo = "/images/pascobyte-logo.svg"
  
  main_css = "/css/bul.min.css"
  secondary_css = "/css/main.css"
  main_js = "/js/main.js"
  single_page_js = "/js/single.js"

  bio = "/my-mission/"
  contact = "https://forms.gle/a6Qb3MYyLbNuFMDDA"
  github = "https://github.com/pascobyte"
  opensea = "https://opensea.io/PascoByte"
  tiktok = "https://www.tiktok.com/@pascobyte"
  youtube = "https://www.youtube.com/channel/UCcPpjsmSJS9p3o9LbLgemaw"

[permalinks]
  chatgpt = "/:filename/"


[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = false