baseURL = 'https://pascobyte.blog/'
languageCode = 'en-us'
title = 'PascoByte'
theme = 'techblog'
disableKinds = ["taxonomy", "term"]
disableHugoGeneratorInject = true
minifyOutput = true
enableRobotsTXT = true

[params]
  tagline = "Ingenewaty Meets Tech Satire!"
  headline = "PascoByte: Unleashing Dutch Wit on Tech Bytes"
  description = "PascoByte: Where Ingenewaty meets Tech Bytes, crafting code, games, and magic with Dutch wit! Unleashing digital dreams from the Netherlands! 🚀"
  logo = "/images/pascobyte-logo.svg"
  bio = "/about/"
  twitter = "https://twitter.com/pascobyte"
  github = "https://github.com/pascobyte"
  opensea = "https://opensea.io/PascoByte"




[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = false