baseURL = 'https://pascobyte.blog/'
languageCode = 'en-us'
title = 'PascoByte'
theme = 'techblog'
disableKinds = ["taxonomy", "term"]
disableHugoGeneratorInject = true
minifyOutput = false
enableRobotsTXT = true

[params]
  tagline = "Explore the latest AI trends, news, and research"
  headline = "The best place to learn about AI and technology"
  intro = "Welcome to PascoByte, your one-stop shop for all things AI and technology. We are passionate about sharing the latest news, trends, and research in this exciting field."
  description = "PascoByte: Stay up-to-date on technology and AI with informative and engaging content."
  logo = "/images/pascobyte-logo.svg"
  bio = "/my-mission/"
  contact = "https://forms.gle/a6Qb3MYyLbNuFMDDA"
  twitter = "https://twitter.com/pascobyte"
  twitterhandle = "@pascobyte"
  github = "https://github.com/pascobyte"
  opensea = "https://opensea.io/PascoByte"

[permalinks]
  chatgpt = "/:filename/"


[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = false