baseURL = 'https://pascobyte.blog/'
languageCode = 'en-us'
title = 'PascoByte'
theme = 'techblog'
disableKinds = ["taxonomy", "term"]
disableHugoGeneratorInject = true
minifyOutput = true
enableRobotsTXT = true

[params]
  tagline = "Exploring AI & Technology"
  headline = "Exploring AI & Technology"
  description = "PascoByte, a personal blog where I explore AI technology like Bard and ChatGPT plus other interesting topics that the world has to offer."
  logo = "/images/pascobyte-logo.svg"
  bio = "/my-mission/"
  contact = "https://forms.gle/a6Qb3MYyLbNuFMDDA"
  twitter = "https://twitter.com/pascobyte"
  github = "https://github.com/pascobyte"
  opensea = "https://opensea.io/PascoByte"

[permalinks]
  chatgpt = "/:filename/"


[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = false